### ISSUE TITLE
Feature Request - New fields for selection when creating PLAYLISTS

### ISSUE THREAD

**Issue by SGDugas1** [wa2c/medoly-issue#3]
Enhancement / Feature Request
PLAYLISTS
Could the Field/Tag RATING WMP and Field/Tag LANGUAGE 
be made available to select songs for a Playlist ?
Thank you

**Comment by wa2c** [comment]
Umm, it so difficult. Android media db doesn't have the information.

**Comment by SGDugas1** [comment]
Thank you for taking the time to address my request.
I must apologize for my lack of knowledge regarding MP3 ID3 frames and the Android media db.
I thought that Medoly scanned the various frames to find the USLT frame to obtain “Unsynchronized Lyrics”. If so, fetching TLAN for “Language” or POPM for “Popularimeter” would also have been possible.
That’s really unfortunate as it would have made Medoly such a powerful and versatile player.
Take care. Steve.

**Comment by SGDugas1** [comment]
Thank you for taking the time to address my request.

I must apologize for my lack of knowledge regarding MP3 ID3 frames and the
Android media db.

I thought that Medoly scanned the various frames to find the USLT frame to
obtain “Unsynchronized Lyrics”. If so, fetching TLAN for “Language” or POPM
for

“Popularimeter” would also have been possible.

That’s really unfortunate as it would have made Medoly such a powerful and
versatile player.

Take care. Steve.
